### ISSUE TITLE
Organization form of UCF101

### ISSUE THREAD

**Issue by chenjiadong96** [mit-han-lab/temporal-shift-module#101]
If I want to run your code on UCF101, what format should UCF101 be organized into? This confuses me. Hope you can tell me. Otherwise, I will need to spend a lot of time to study how to organize the UCF101 data set to meet the code. Looking forward to your reply, thanks

**Comment by tonylins** [comment]
Sorry for the late reply. For UCF 101, please refer to TSN repo for the data structure. Basically, you will need a file of video list for training.

**Comment by Nauman007** [comment]
hi @chenjiadong96  did u solve it ? can u guide me ?
