### ISSUE TITLE
learning rate multiplied by 0.1 while printing

### ISSUE THREAD

**Issue by Griffintaur** [mit-han-lab/temporal-shift-module#104]
learning rate is multiplied by 0.1 while printing in logs(https://github.com/mit-han-lab/temporal-shift-module/blob/master/main.py#L274) while printing after each epoch authors are not multiplying it by 0.1(https://github.com/mit-han-lab/temporal-shift-module/blob/master/main.py#L282)?
Is it a typo in there?

**Comment by tonylins** [comment]
Hi, for most of the experiments we used 10x lr for the final classification layer, so we multiply it by 0.1 to print the overall lr. It is indeed a todo fix.

**Comment by Griffintaur** [comment]
Thanks for the clarification

**Comment by tonylins** [comment]
I will close the issue for now. Feel free to re-open if you have further problems.
