### ISSUE TITLE
Why the shift direction implemented in the code is opposite to that described in the paper？

### ISSUE THREAD

**Issue by chenjiadong96** [mit-han-lab/temporal-shift-module#106]
Why is the shift direction implemented in the code opposite to what the paper describes? In the code, some channels are moved up in the frame dimension and then another part is moved down. But the original shift operation described in Figure 1 is to move down and then up. There is a difference between the two, because I experimented with these two schemes and got different accuracy.
![1592377362(1)](https://user-images.githubusercontent.com/65204425/84866408-419ea180-b0ac-11ea-96ad-993f5714c655.png)
![1592377419(1)](https://user-images.githubusercontent.com/65204425/84866416-4400fb80-b0ac-11ea-9889-e23056f01e50.png)

**Comment by tonylins** [comment]
Hi, actually I think these two implementation are identical, since the channels are order-agnostic (convolutions are fully connected in channel dimension). How different are the results you got?

**Comment by tonylins** [comment]
Close due to inactivity. Feel free to reopen.
