### ISSUE TITLE
Could you provide your training configs for sth V1 & V2?

### ISSUE THREAD

**Issue by dreamerlin** [mit-han-lab/temporal-shift-module#109]
Can you provide your training configs for sth V1 & V2?
I try to train the TSN and TSM in your repo, but I do not find the training config (lr, batch_size, wd, etc). So I just use the setting in the default script, but I didn't get the top1 & top5 score in your modelzoo. Could you provide them?

**Comment by tonylins** [comment]
Please find the training script in README:

```
python main.py something RGB \
     --arch resnet50 --num_segments 8 \
     --gd 20 --lr 0.01 --lr_steps 20 40 --epochs 50 \
     --batch-size 64 -j 16 --dropout 0.5 --consensus_type=avg --eval-freq=1 \
     --shift --shift_div=8 --shift_place=blockres --npb
```

**Comment by dreamerlin** [comment]
The training script is used for training TSM Sthv1 8 frame. I wish you could provide more training scripts for SthV2 or Sthv1 with 16 frames etc. The [table](https://github.com/mit-han-lab/temporal-shift-module#something-something) shows results for 6 setting, but only one training scripts for TSM Sthv1 8 frame is provided.

**Comment by tonylins** [comment]
Just change `--num_segments 8` to `--num_segments 16`, every other hyper-parameters are the same.
