### ISSUE TITLE
mobilenetv2 on somethingsomethingv2 performance?

### ISSUE THREAD

**Issue by dragen1860** [mit-han-lab/temporal-shift-module#111]
Dear author:
  you make a gesture demo using mobv2, which is really helpful!
  I wonder have you tried trainining on other large actions space datasets, such as full sthsthv2 , using mobilenetv2？ could you give some intuitive performance descrption of mobv2 on these datasets? thank you.

**Comment by tonylins** [comment]
Hi, thanks for your interests. But I did not train MobileNetV2 on the Something-Something dataset.
