### ISSUE TITLE
Test time increase linearly then crashed for RecursionError

### ISSUE THREAD

**Issue by tradysun** [mit-han-lab/temporal-shift-module#118]
I test several videos, but the predict time increase linearly, may increase from 200ms to 3s (even more). Then the test script crashed for RecursionError: maximum recursion depth exceeded. I this the reason is out of memory in net. Any suggestions?

**Comment by tonylins** [comment]
What is the test script you used? And what is the error log?

**Comment by tradysun** [comment]
> What is the test script you used? And what is the error log?

I wrote a test script based on test_models.py to test multiply videos(download from url, decode with ffmpeg). I found it is my fault (repeated initialization) when test videos in a for loop which cause out of memory (RecursionError: maximum recursion depth exceeded). I have figured out the issue. Anyway, thanks for your replay.
