### ISSUE TITLE
which inference engine used for deploying on android phone?

### ISSUE THREAD

**Issue by dragen1860** [mit-han-lab/temporal-shift-module#119]
Dear author:
   I noticed the bi-directional model can not be exported directly to Coreml/MNN mobile engines, since it used 5-dim tensors and the Scatter ops. I wonder have you done some modification to the original bi-directional models, or did you use other powerful mobile inference engines？ thank you.

**Comment by dandingol03** [comment]
Hi, i was wandering how can i deploy this model to mobile , have you figured out the method?
