### ISSUE TITLE
Division by 2 in total no of frames calculation for each video 

### ISSUE THREAD

**Issue by Griffintaur** [mit-han-lab/temporal-shift-module#120]
Herein each of the videos, the total number of frames are divided by 2 when image_tmpl is form  '{:06d}-{}_{:05d}.jpg'. I couldn't understand what's the specific reason behind it?
https://github.com/mit-han-lab/temporal-shift-module/blob/f09f42db80f1dbeaf9c7448fbd491cd59043e711/ops/dataset.py#L103

**Comment by tonylins** [comment]
Hi, you can ignore the code. That should be a hack when I process one of the datasets.
