### ISSUE TITLE
Could you please provide your training config for I3D NL and TSM NL?

### ISSUE THREAD

**Issue by dreamerlin** [mit-han-lab/temporal-shift-module#121]
Could you please provide your training config for I3D NL and TSM NL in this [table](https://github.com/mit-han-lab/temporal-shift-module#dense-sample)? Besides,the training scripts in this repo are not full provided and it is hard to reproduce the results for each setting.

**Comment by tonylins** [comment]
The I3D NL results are taken from the non-local paper. Please follow non-local paper for the training setting.

For TSM NL training script, you can just add --non_local arg to Kinetics training script below. All other hyper-parameters are the same.
```
python main.py kinetics RGB \
     --arch resnet50 --num_segments 8 \
     --gd 20 --lr 0.02 --wd 1e-4 --lr_steps 20 40 --epochs 50 \
     --batch-size 128 -j 16 --dropout 0.5 --consensus_type=avg --eval-freq=1 \
     --shift --shift_div=8 --shift_place=blockres --npb
```
