### ISSUE TITLE
Cuda out of memory (UCF101)

### ISSUE THREAD

**Issue by Nauman007** [mit-han-lab/temporal-shift-module#122]
hi I am getting the following errror while traning on UCF101.
below are the details ... can someone guide me ...? @tonylins 

![image](https://user-images.githubusercontent.com/32773342/87655854-2dfd5e00-c772-11ea-88f8-31b28f80486a.png)
![image](https://user-images.githubusercontent.com/32773342/87655955-4bcac300-c772-11ea-8f49-012592a4927e.png)

**Comment by tonylins** [comment]
Hi, it means that the GPU memory is not enough to hold the batch size. The script you run is intended for training with 8 GPUs (>80GB GPU memory in total). However, on Colab, you can only access one.

**Comment by Nauman007** [comment]
from where i can change the gpu count to 1 from 8?

**Comment by tonylins** [comment]
You can use your own lab servers or use AWS/GCP to create cloud instances (might be expensive).

**Comment by Nauman007** [comment]
is there a way i can follow your code using 1 GPU ?

**Comment by Nauman007** [comment]
Sorry for the DUMB questions ...

**Comment by tonylins** [comment]
You can reduce the batch size and learning rate by 8. However, the performance might be worse.

**Comment by Nauman007** [comment]
if i reduce the batch-size to 8 , what should be the value of lr ?

**Comment by tonylins** [comment]
You should also reduce the lr by 8x, if you reduce the batch size by 8x.

**Comment by Nauman007** [comment]
OK i was worried about the file list i created seems like my issues are because of GPU.
thanks for the answers... I'll contact if i face further issues.

**Comment by Nauman007** [comment]
if batch size = 32, 
lr = 0.001/2 = 0.0005?

**Comment by Nauman007** [comment]
reducing the batch size doesnt help now it gives 

RuntimeError: CUDA out of memory. Tried to allocate 98.00 MiB (GPU 0; 11.17 GiB total capacity; 10.73 GiB already allocated; 25.81 MiB free; 10.83 GiB reserved in total by PyTorch)

batch size = 8
lr = 0.00025

**Comment by Nauman007** [comment]
what prerequisites you would suggest we should before start working with this model ?

**Comment by tonylins** [comment]
Batch size 16 might be still too big for a single GPU, you may want to try 8 (64/8=8). But I think the performance will be hurt.

**Comment by Nauman007** [comment]
I get this error if i set batch-size= 8, lr = 0.001/8 = 0.000125

**THCudaCheck FAIL file=/pytorch/aten/src/THC/THCCachingHostAllocator.cpp line=278 error=710 : device-side assert triggered
Traceback (most recent call last):
  File "/content/temporal-shift-module-master/main.py", line 378, in <module>
    main()
  File "/content/temporal-shift-module-master/main.py", line 194, in main
    train(train_loader, model, criterion, optimizer, epoch, log_training, tf_writer)
  File "/content/temporal-shift-module-master/main.py", line 248, in train
    prec1, prec5 = accuracy(output.data, target, topk=(1, 5))
  File "/content/temporal-shift-module-master/ops/utils.py", line 33, in accuracy
    _, pred = output.topk(maxk, 1, True, True)
RuntimeError: cuda runtime error (710) : device-side assert triggered at /pytorch/aten/src/THC/generic/THCTensorSort.cu:151
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered (insert_events at /pytorch/c10/cuda/CUDACachingAllocator.cpp:771)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x46 (0x7f6fbb510536 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #1: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x7ae (0x7f6fbb753fbe in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10_cuda.so)
frame #2: c10::TensorImpl::release_resources() + 0x4d (0x7f6fbb500abd in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #3: <unknown function> + 0xa2aae9 (0x7f6ff3e4cae9 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x2908890 (0x7f6ff5d2a890 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x2d8c222 (0x7f6ff61ae222 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #6: torch::autograd::deleteNode(torch::autograd::Node*) + 0x7f (0x7f6ff61ae2cf in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0x3b3c19 (0x7f700298dc19 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #8: c10::TensorImpl::release_resources() + 0x20 (0x7f6fbb500a90 in /usr/local/lib/python3.6/dist-packages/torch/lib/libc10.so)
frame #9: <unknown function> + 0x5230f2 (0x7f7002afd0f2 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #10: <unknown function> + 0x523196 (0x7f7002afd196 in /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch_python.so)
frame #11: python3() [0x54ef16]
frame #12: python3() [0x588948]
frame #13: python3() [0x5ad438]
frame #14: python3() [0x5ad44e]
frame #15: python3() [0x5ad44e]
frame #16: python3() [0x56b276]
<omitting python frames>
frame #22: __libc_start_main + 0xe7 (0x7f700699eb97 in /lib/x86_64-linux-gnu/libc.so.6)**

**Comment by Nauman007** [comment]
I get this error if i set batch-size= 8, lr = 0.001/8 = 0.000125

![image](https://user-images.githubusercontent.com/32773342/88421531-2721bb80-ce02-11ea-857e-6b98136055bc.png)

**Comment by tonylins** [comment]
Hi, these are not questions related to this repo. I think you can use Google for these questions.

**Comment by Nauman007** [comment]
hi, how about resizing of the images to (64,64,3) in the __loadImg__() function in dataset.py snippet ?
current size of the extracted frames is (320,240,3)

**Comment by Nauman007** [comment]
hi, sorry, one more question i have picked 7 classes only from UCF101 ,still it is not fitting into gpu memory ... i wonder what am i doing wrong... @tonylins i am unable to identify what is the root of the problem,
