### ISSUE TITLE
How to get the online demo running on a lightweight device like Samsung Galaxy?

### ISSUE THREAD

**Issue by Fritskee** [mit-han-lab/temporal-shift-module#123]
In your paper you mention that TSM can run on a device like the Samsung Galaxy S8. What changes are needed to setup the online demo on such a device?

**Comment by tonylins** [comment]
Hi, we only used TVM to measure the inference timing on these devices but did not set up the gesture recognition demo on Galaxy S8. For smartphones like Galaxy S8, I assume that you may need to do some Android programmings for data IO (e.g., reading from the camera).

**Comment by Fritskee** [comment]
Alright, thanks for the reply! I wasn't aware that it was only the TVM that was tested on the Galaxy.

**Comment by Nauman007** [comment]
@tonylins kindly address this issue also #122

**Comment by tonylins** [comment]
I will close the issue for now. Feel free to reopen.

**Comment by dandingol03** [comment]
Hi, @tonylins @Fritskee , so what do i need to make the online demo run on an android device? I read the online-demo readme, but i am not sure what step can i skip. Do i need the TVM compile step？ Hope to get your guys' replay, thanks in advance~

**Comment by dandingol03** [comment]
Hi @Fritskee , Thank for your kindly replay, i will try it
