### ISSUE TITLE
How should "file_list" look like for UCF101 to feed it to the network (Confused)

### ISSUE THREAD

**Issue by Nauman007** [mit-han-lab/temporal-shift-module#124]
Can someone tell me what should fileList look like so that i can start training my model. i have attached the list i generated,

[ucf101_rgb_val_split_1.txt](https://github.com/mit-han-lab/temporal-shift-module/files/4966806/ucf101_rgb_val_split_1.txt)
[ucf101_rgb_train_split_1.txt](https://github.com/mit-han-lab/temporal-shift-module/files/4966808/ucf101_rgb_train_split_1.txt)

PS: My rest of the list_file look like the above .

**Comment by tonylins** [comment]
The file list you provided seems to be in the right format. Let me know if you have problems training with the file list.
