### ISSUE TITLE
How to save the score for two stream fusion

### ISSUE THREAD

**Issue by anzheng13** [mit-han-lab/temporal-shift-module#125]
Thanks for your opening code.I want to fusion the RGB stream and optical flow stream like the TSN,but I don't know how to save the score when testing .

**Comment by tonylins** [comment]
Hi, the `test_model.py` file actually supports multi-model/multi-modality fusion in a nasty way (e.g., https://github.com/mit-han-lab/temporal-shift-module/blob/master/test_models.py#L98). You can check the arg definition to find how to test the models with two-stream.

**Comment by anzheng13** [comment]
Thank you.



---Original---
