### ISSUE TITLE
what does 8*10 clips means?

### ISSUE THREAD

**Issue by dragen1860** [mit-han-lab/temporal-shift-module#126]
Dear all:
  I wonder what does 8*10 clips means? I know the 8 means 8 frames for each clips. I dont understand what does 10 means? thank you very much.

**Comment by Nauman007** [comment]
@dragen1860 have u anyidea about issue #124 and #122 ,any help would be much appreciated ... i cant start my training process... :(

**Comment by tonylins** [comment]
Hi, it means that during testing, we sample 10 clips from the video, and use the average prediction as the video prediction. It is a common practice in Kinetics training&evaluation. You can check https://arxiv.org/pdf/1812.03982.pdf for some details.

**Comment by tonylins** [comment]
Hi @Nauman007, please do not refer irrelevant issues in other threads :)
