### ISSUE TITLE
No such file or directory: '/ssd/video/something/v1/category.txt'

### ISSUE THREAD

**Issue by ysl208** [mit-han-lab/temporal-shift-module#132]
I get the following error 
```
Traceback (most recent call last):
  File "test_models.py", line 126, in <module>
    modality)
  File "/home/usr/Projects/temporal-shift-module/ops/dataset_config.py", line 117, in return_dataset
    with open(file_categories) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/ssd/video/something/v1/category.txt'
```

when running

```
python test_models.py something \
    --weights=pretrained/TSM_something_RGB_resnet50_shift8_blockres_avg_segment8_e45.pth \
    --test_segments=8 --batch_size=72 -j 24 --test_crops=3  --twice_sample
```
I'm not sure what it's looking for?

**Comment by Nauman007** [comment]
adjust the path accordingly in dataset_config.py , provide the path to category.txt file according to your directory

**Comment by ysl208** [comment]
I downloaded the something dataset and it doesn't seem to have a category.txt file? Is it from [here](https://20bn.com/datasets/something-something/v2#download)?

**Comment by Nauman007** [comment]
i havent worked with something something dataset .. but i am sure you can find the labels of something something dataset from the internet

**Comment by ysl208** [comment]
On which dataset did you manage to get it running ?
I checked and the sources don't have the `category.txt` files, for Something something but also not for Jester.

**Comment by MattVil** [comment]
@ysl208 The categories.txt file is just the list of your recognized actions. You can make a small script to create it of do it bye hand
