### ISSUE TITLE
python3: can't open file 'main.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Bkaavya** [mit-han-lab/temporal-shift-module#143]
![Gesture control Error](https://user-images.githubusercontent.com/72389313/95075193-69824580-072d-11eb-85aa-04779425fd63.png)

Hi  all,

Please check the attached error am getting while running the tutorial , Please help me out  how to solve it.

am so new to it.

Regards ,
kaavya

**Comment by tonylins** [comment]
please run `cd ..` before run `python3 main.py`. I have updated the README.

**Comment by Bkaavya** [comment]
still i am facing the same issue 
please just look itno it

**Comment by Bkaavya** [comment]
![Uploading Gesture detction error 2.png…]()

**Comment by Nauman007** [comment]
@Bkaavya  you need to see where your main.py is , go to the respective directory and locate main.py file and then run main.py
