### ISSUE TITLE
TSN only uses 1 segment?

### ISSUE THREAD

**Issue by zhengshou** [mit-han-lab/temporal-shift-module#144]
Hi, maybe I am missing something, but according to log like the below one, looks like when using TSN 2D model, only 1 test_segment, i.e. 1 frame is used? I thought it is supposed to average results from input frames, say 8 frames?

https://file.lzhu.me/projects/tsm/models/log/testlog_uniform_TSM_kinetics_RGB_resnet50_avg_segment5_e50.log

Thanks!

**Comment by tonylins** [comment]
Hi, sorry for the confusion. The `num_segments` parameter is used only when you enable TSM or Non-local in this codebase. For TSN, the parameter is not considered. But during testing, we feed 8 frames into the TSN model.

**Comment by zhengshou** [comment]
Got it, thanks Ji!
