### ISSUE TITLE
[Resolved] Error while training with Mobilenet Architecture

### ISSUE THREAD

**Issue by Nauman007** [mit-han-lab/temporal-shift-module#145]
I am facing this error while training with mobilenet architecture...any solutions..?
-------------------------------------------------------------------------------------------------------------------------------------------------------------------
ucf101: 6 classes
storing name: TSM_ucf101_RGB_mobilenetv2_shift8_blockres_avg_segment8_e25
creating folder log
creating folder checkpoint
creating folder log/TSM_ucf101_RGB_mobilenetv2_shift8_blockres_avg_segment8_e25
creating folder checkpoint/TSM_ucf101_RGB_mobilenetv2_shift8_blockres_avg_segment8_e25

    Initializing TSN with base model: mobilenetv2.
    TSN Configurations:
        input_modality:     RGB
        num_segments:       8
        new_length:         1
        consensus_module:   avg
        dropout_ratio:      0.8
        img_feature_dim:    256
            
=> base model: mobilenetv2
Downloading: "https://www.dropbox.com/s/47tyzpofuuyyv1b/mobilenetv2_1.0-f2a8633.pth.tar?dl=1" to /root/.cache/torch/hub/checkpoints/mobilenetv2_1.0-f2a8633.pth.tar
100% 13.5M/13.5M [00:00<00:00, 64.8MB/s]
Traceback (most recent call last):
  File "/content/temporal-shift-module/main.py", line 378, in <module>
    main()
  File "/content/temporal-shift-module/main.py", line 65, in main
    non_local=args.non_local)
  File "/content/temporal-shift-module/ops/models.py", line 59, in __init__
    self._prepare_base_model(base_model)
  File "/content/temporal-shift-module/ops/models.py", line 144, in _prepare_base_model
    if self.print_spec:
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 772, in __getattr__
    type(self).__name__, name))
**torch.nn.modules.module.ModuleAttributeError: 'TSN' object has no attribute 'print_spec**

**Comment by sarsigmadelta** [comment]
https://user-images.githubusercontent.com/28585937/102880620-96b9d680-4486-11eb-8214-b070ef66c6e0.mp4

**Comment by yushuinanrong** [comment]
How did you resolve this issue?

**Comment by Nauman007** [comment]
Hi, good day
go to models.py file stored in ops folder and add line# 35 to models.py file
![image](https://user-images.githubusercontent.com/32773342/103380957-2c4f0900-4b0c-11eb-84a3-7a66a7206126.png)
