### ISSUE TITLE
Where is the code for 10 clips testing?

### ISSUE THREAD

**Issue by mitming** [mit-han-lab/temporal-shift-module#158]
I have read your code and paper, in your paper, *For testing, when pursue high accuracy, we followed the common setting in [49, 50] to sample multiple clips per video (10 for Kinetics, 2 for others)*

I found sample 2 clips per video in your [code](https://github.com/mit-han-lab/temporal-shift-module/blob/7192eaa324f7e2aebfb362299bf11354d61f785d/ops/dataset.py#L153), but I cannot find 10 clips test for kinetics.

I'll appreciate that if you could reply me!

**Comment by tonylins** [comment]
Hi, we provide the testing script for Kinetics in README
```
python test_models.py kinetics \
    --weights=pretrained/TSM_kinetics_RGB_resnet50_avg_segment5_e50.pth \
    --test_segments=8 --test_crops=3 \
    --batch_size=8 --dense_sample --full_res
```

where `--dense_sample` corresponds to the 10 clips testing.

**Comment by mitming** [comment]
Thanks a lot! Sorry to bother you.



---Original---
