### ISSUE TITLE
Can you share the repository of kinectics 400 dataset that you had used for training?

### ISSUE THREAD

**Issue by malarsaravanan1991** [mit-han-lab/temporal-shift-module#19]
Hi,

Thank you for your work . I was trying to use the TSM module and also check with the reported accuracy but the test_models.py is expecting a val_folder.txt and train_folder.txt(basically train and validation file list).
I tried to download the kinetics 400 data set(download from official code from the script in activity net) but the recent one has so many expired/broken YouTube links . If possible could you please give access to the kinetics data set that you used for training?.

**Comment by tonylins** [comment]
Hi, you may consider using the archived version of Kinetics from the non-local network repo, which should produce a similar result:
https://github.com/facebookresearch/video-nonlocal-net/blob/master/DATASET.md
