### ISSUE TITLE
Missing mobilenet_v2_tsm_v2 file

### ISSUE THREAD

**Issue by kdy1999** [mit-han-lab/temporal-shift-module#196]
@JoshNoel Hi, when running mobilenet_v2_tfslim.py, there is an error on line 119
mobilenet_v2_tsm_v2.py is missing in the tsm fpga folder
![image](https://user-images.githubusercontent.com/30910741/128017828-2af3b05c-66c1-4085-91c9-f7e9914f211e.png)

**Comment by DatCanCode** [comment]
Did you find mobilenet_v2_tsm_v2.py?
