### ISSUE TITLE
could you share a copy of something something v2

### ISSUE THREAD

**Issue by caopulan** [mit-han-lab/temporal-shift-module#197]
This dataset is unavailable now on TwentyBN website. could you share it on drive please? Thanks a lot.

**Comment by waduhekx** [comment]
hi, caopulan.
did you got this dataset ready? if that ,can you share to me ? thanks a lot.

my email: 405676567@qq.com or himteeem@hotmail.com

**Comment by caopulan** [comment]
> hi, caopulan.
> did you got this dataset ready? if that ,can you share to me ? thanks a lot.
> 
> my email: [405676567@qq.com](mailto:405676567@qq.com) or [himteeem@hotmail.com](mailto:himteeem@hotmail.com)

还没有，但是找到个有这个数据集的朋友，在问能不能上传网盘分享给我。给我的话我发你邮箱~

**Comment by waduhekx** [comment]
好的好的，多谢啦，兄dei

**Comment by waduhekx** [comment]
> > hi, caopulan.
> > did you got this dataset ready? if that ,can you share to me ? thanks a lot.
> > my email: [405676567@qq.com](mailto:405676567@qq.com) or [himteeem@hotmail.com](mailto:himteeem@hotmail.com)
> 
> 还没有，但是找到个有这个数据集的朋友，在问能不能上传网盘分享给我。给我的话我发你邮箱~

链接：https://pan.baidu.com/s/1YBEMhvTb1TvPzpwSM_pVog 提取码：4bqc
我找到了，上面这个就是something-something v2数据集的百度云链接
