### ISSUE TITLE
Legacy autograd function with non-static forward method is deprecated and will be removed in 1.3. Please use new-style autograd function with static forward method

### ISSUE THREAD

**Issue by whut09** [mit-han-lab/temporal-shift-module#20]
when run the repo, it will keep poping the UserWarning:
/pytorch/torch/csrc/autograd/python_function.cpp:638: UserWarning: Legacy autograd function with non-static forward method is deprecated and will be removed in 1.3. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)

os:win7
pytorch:1.2
python:3.5

**Comment by tonylins** [comment]
Hi, thanks for pointing out. When writing the code, we used some older version of PyTorch. Feel free to update the code to use the new api!

**Comment by jiamingNo1** [comment]
@whut09 According to pytorch docs about autograd function, modify the basic_ops.py module and you can eliminate this warning.

**Comment by whut09** [comment]
thanks , I solved it ,  modify the basic_ops.py  forward function, use @staticmethod can eliminate this warning.
