### ISSUE TITLE
TSM model checkpoint download links are unavailable!

### ISSUE THREAD

**Issue by jianghaojun** [mit-han-lab/temporal-shift-module#200]
All the download links encounter the 404 Not Found error!

**Comment by guuzaa** [comment]
Hi @tonylins,
I have encountered with the same problem.  Could you share the checkpoints with us again?
Thanks for your wonderful work.

**Comment by tonylins** [comment]
Hi, the download links have been fixed. Please check if it works. Thanks!

**Comment by guuzaa** [comment]
> Hi, the download links have been fixed. Please check if it works. Thanks!

I have checked. The checkpoint links work now. Thanks for your time :)
