### ISSUE TITLE
The link of pretrained model is broken, please check it.Thanks!

### ISSUE THREAD

**Issue by yubin2020** [mit-han-lab/temporal-shift-module#209]

**Comment by tonylins** [comment]
Hi, which link is missing? Thanks!

**Comment by yubin2020** [comment]
All the link,I and my frends try many times, the links don't work! Garbled code！

**Comment by tonylins** [comment]
Please download the weights using something like `wget` or right click save as. The browser cannot interpreter `.pth`.

**Comment by yubin2020** [comment]
Thanks!
