### ISSUE TITLE
The testing speed on Jeston Nano

### ISSUE THREAD

**Issue by Neptunelover** [mit-han-lab/temporal-shift-module#210]
Hi, I have deployed the projected successfully on the Jeston Nano, but the testing speed is just 0.7vid/s. I noticed that this was no accident. I think it may be caused by onnx. I used onnx==1.6.0 and onnx-simplifier==0.2.18.
Could you offer some suggestion on this issue? Thanks!

**Comment by xxxlive** [comment]
Have you solved this problem? I also meet the same problem.

**Comment by xxxlive** [comment]
Maybe you are lacking of tophub file

**Comment by Neptunelover** [comment]
> Maybe you are lacking of tophub file

Yeah, thats right. When I download the tophub files, the testing speed achieved 30vid/s. Thanks for your help!

**Comment by huntlin** [comment]
> > 也许你缺少 tophub 文件
> 
> 是啊，没错。当我下载 tophub 文件时，测试速度达到了 30vid/s。谢谢你的帮助！

Where can I download the tophub file and how to use it?

**Comment by xxxlive** [comment]
> > > 也许你缺少 tophub 文件
> > 
> > 
> > 是啊，没错。当我下载 tophub 文件时，测试速度达到了 30vid/s。谢谢你的帮助！
> 
> Where can I download the tophub file and how to use it?

你可以看一下这个，https://discuss.tvm.apache.org/t/warningfailed-to-download-tophub-package-for-llvm-urlopen-error-errno-111-connection-refused/5759/5
然后我是直接把那个网站的ip地址配到了本机的dns里，然后就下载下来了
