### ISSUE TITLE
Acc1 about training HMDB51 pretrained on Imagenet

### ISSUE THREAD

**Issue by VanChilly** [mit-han-lab/temporal-shift-module#219]
I use the code(also the script for ucf) train the HMDB51 datasets and the resnet50 pretrained on imagenet. Finally I got 51% top1 Acc, is that reasonable?
I just want to know whether i got a reasomable results. Thank you very much

**Comment by VanChilly** [comment]
this is my command
```shell
python -u main.py hmdb51 RGB --arch resnet50 --num_segments 8 --gd 20 --lr 0.001 --lr_steps 10 20 --epochs 25 --batch-size 8 -j 8 --dropout 0.8 --consensus_type=avg --eval-freq=1 --shift --shift_div=8 --shift_place=blockres > log.log
```

**Comment by zhoubin-me** [comment]
same here, maximum 51% acc for 50 epochs at [20, 40] decay.

**Comment by zhoubin-me** [comment]
@VanChilly I think the result are obtained by a pre-trained model from K400 then finetune on HMDB

**Comment by VanChilly** [comment]
> same here, maximum 51% acc for 50 epochs at [20, 40] decay.

So, it's clear that the result is reasonable for HMDB pre-trained on ImageNet. 👍

**Comment by VanChilly** [comment]
> @VanChilly I think the result are obtained by a pre-trained model from K400 then finetune on HMDB

Yeah, the author mentioned that in the paper. Thank you.
