### ISSUE TITLE
如果不用预训练模型，从头训练，opts.py文件里的参数该如何配置

### ISSUE THREAD

**Issue by TimeChi** [mit-han-lab/temporal-shift-module#22]
我没有加载预训练模型，backbone用的resnet50，但是一直不收敛。希望作者大大帮忙解答，谢谢！

**Comment by tonylins** [comment]
如果 train from scratch，可以考虑将initial learning rate调大10倍，并且打开--npb，其他应该不需要修改。

另外注意batch size不可过小。

**Comment by TimeChi** [comment]
> 如果 train from scratch，可以考虑将initial learning rate调大10倍，并且打开--npb，其他应该不需要修改。
> 
> 另外注意batch size不可过小。

谢谢作者大大的回复，我打开--npb和--shift之后网络开始正常的训练了。
我想问一下关于--shift_div这个参数怎么设置合适，是根据--num_segments的值设置么

**Comment by tonylins** [comment]
`--shift_div`一般设为8，我在所有的setting下都用的这个参数，应该不需要修改。

**Comment by sunnymoon155** [comment]
@tonylins 请问batch size最小可以设置多少呢？我的配置只允许设置到16，可是从头训练了8个epoch的kinetics数据集，prec@1 performance只有57%，提升很慢，我看repo中可以达到71.2%

**Comment by tonylins** [comment]
@sunnymoon155 考虑到BN的使用，最好每张卡上能使用8的batch size。否则得使用syncBN才能保证训练的稳定。
