### ISSUE TITLE
the pretrained model link is broken. It shows as text but not downloading

### ISSUE THREAD

**Issue by SHMCU** [mit-han-lab/temporal-shift-module#224]
The pretrained model links are broken. Downloading does not start, the pth file shows up in a webpage as texts.

**Comment by tonylins** [comment]
Please right click - save as, or use wget

**Comment by SHMCU** [comment]
Thank you! It works.
    On Saturday, September 10, 2022 at 10:06:50 PM PDT, Ji Lin ***@***.***> wrote:  
 
 


Please right click - save as, or use wget
