### ISSUE TITLE
Can the model run in mac cpu mode?

### ISSUE THREAD

**Issue by OptimusPrimeCao** [mit-han-lab/temporal-shift-module#25]

**Comment by tonylins** [comment]
Yes, you can run the demo on Mac CPU with some minor modifications. We may add the tutorial in the future.

**Comment by songkevinc** [comment]
any updates on this? I'm having trouble trying to run the `online_demo` on a Mac

**Comment by songkevinc** [comment]
you can just use the code in the following issue: #148
