### ISSUE TITLE
The model performance of train-from-scratch models

### ISSUE THREAD

**Issue by duducheng** [mit-han-lab/temporal-shift-module#27]
Hi,

Thanks for your amazing work!

I'm new in video analysis, I'm wondering the model performance if you do not load ImageNet pretrained weights? And what if you load pretrained weights on other task dataset, e.g, detecton on MS-COCO?

I did not find you report this issue in your paper or your code, thanks for your help!

**Comment by tonylins** [comment]
According to the SlowFast paper, you should be able to get the similar accuracy when training from scratch on Kinetics.
