### ISSUE TITLE
About 3D Network？

### ISSUE THREAD

**Issue by YongkunZhan** [mit-han-lab/temporal-shift-module#29]
Hello！Thanks for your excellent work.I find there are very little 3D works for sthv1/v2 datastes.
I check the leaderboard of sthv2.The top methods nearly all 2D.The performance of 3D is far away 2D works. In fact ,3D conv is proved more suitable for capturing space-time information.The top Acc of UCF/HMDB/Kinetics are all 3D methods.
So what's your opinions about there are fewer 3D works and their Acc are lower on sthv1/v2?
Looking forward to your reply soon.Thanks.

**Comment by innerlee** [comment]
tsm is some kind of 3d

**Comment by fountain-K** [comment]
> tsm is some kind of 3d
Hello！ Thanks for your reply.However I can not understand your answer well.
The computational cost of 2D conv a image 10 times is less than using 3D conv 10 images .
In TSM paper,it said:

> it can achieve the performance of 3D CNN but maintain 2D CNN’s complexity.

**Comment by tonylins** [comment]
Hi, I think TSM is some kind of 3D network, at a lower cost.
