### ISSUE TITLE
run the online_demo by using my trained model

### ISSUE THREAD

**Issue by noahzhy** [mit-han-lab/temporal-shift-module#30]
I got into a trouble when I run the online_demo by using my trained model.
My trained model has only 4 classes, but an unexpected error occurred. The error message is as follows.
```  
File "main.py", line 319, in main
    cv2.putText(label, 'Prediction: ' + catigories[idx],

IndexError: list index out of range
```
I have modified catigories as 4 classes.

It seems like a simple bug but I don't have a clue about it.

**Comment by noahzhy** [comment]
Does anyone could help me?

**Comment by forbiddenname** [comment]
hi have u solved it？

**Comment by noahzhy** [comment]
> hi have u solved it？
yep, I solved it. If you train your own dataset and run the author's demo before, just delete the file generated by running the demo.

**Comment by NB-Xie** [comment]
Hi , have you met the similar issues like:
https://github.com/mit-han-lab/temporal-shift-module/issues/39#issuecomment-878109917
