### ISSUE TITLE
Use my own data

### ISSUE THREAD

**Issue by jwdwzxd** [mit-han-lab/temporal-shift-module#31]
Thanks a lot for the author's code, the effect is amazing. But I have a problem and I am looking forward to helping: I have implemented the real-time pre-processing of the video frame captured by the webcam, and then how to use this model for motion recognition?
Can someone give me some advice, thank you very much!

**Comment by tonylins** [comment]
Hi, I would suggest referring to the code in `online_demo/main.py`. It contains the full pipeline of recognizing the video stream from a webcam.

**Comment by jwdwzxd** [comment]
Thanks for your quick reply. I will try it according to your ideas. Thank you again!

**Comment by forbiddenname** [comment]
> Thanks for your quick reply. I will try it according to your ideas. Thank you again!

hi have you solved it ？i want to use this model for online motion recognition, like sth-sth, can u give me some advices?

**Comment by Nauman007** [comment]
hi @forbiddenname  can u guide me how i can train my custom dataset on thiis model ?
