### ISSUE TITLE
how to test on a movie? mp4 or avi  

### ISSUE THREAD

**Issue by ucasiggcas** [mit-han-lab/temporal-shift-module#41]
hi, dear,
have tested the test_models.py a liittle difficult to read,
if I just want to test on some movies ,then how should I modify the codes,
thx

any advice or suggsetion will be appreciated.

if have a key argument 'video_path' will be more convenient 
do not want test on the txt file below
```
Traceback (most recent call last):
  File "test_models.py", line 182, in <module>
    ]), dense_sample=args.dense_sample, twice_sample=args.twice_sample),
  File ".\temporal-shift-module\ops\dataset.py", line 58, in __init__
    self._parse_list()
  File ".\temporal-shift-module\ops\dataset.py", line 96, in _parse_list
    tmp = [x.strip().split(' ') for x in open(self.list_file)]
FileNotFoundError: [Errno 2] No such file or directory: '/ssd/video/kinetics/labels/val_videofolder.txt'
```

**Comment by ucasiggcas** [comment]
could u pls supply the txt file ?
`'/ssd/video/kinetics/labels/val_videofolder.txt'`

**Comment by tonylins** [comment]
Duplicated issue to #42
