### ISSUE TITLE
where is archs.small_resnet.ResNet?

### ISSUE THREAD

**Issue by ucasiggcas** [mit-han-lab/temporal-shift-module#45]
hi,dear
in the script [non_local.py](https://github.com/mit-han-lab/temporal-shift-module/blob/master/ops/non_local.py#L135)
I find the **archs.small_resnet.ResNet**
but in the [archs/](https://github.com/mit-han-lab/temporal-shift-module/tree/master/archs) I couldn't find it 
So could you help me ?
thx

**Comment by tonylins** [comment]
Hi, sorry for the confusion. small_resnet is not expected to appear in the codebase. I will remove that.
