### ISSUE TITLE
Pretrained model on Kinetics with input of Optical Flow

### ISSUE THREAD

**Issue by misunusc** [mit-han-lab/temporal-shift-module#48]
Hi Dr Lin,
Did you train TSM on Kinetics dataset using optical flow as the input modality?
If so, could you please release the pre-trainded model on Kinetics with the input of optical flow?
Thank you!

**Comment by tonylins** [comment]
Hi, currently I have not prepared the flow model. But it seems that this is a common request, I will try to provide it ASAP. Thanks for waiting!

**Comment by tonylins** [comment]
Hi, you can find a beta/informal pre-trained model on Kinetics flow here: https://hanlab.mit.edu/projects/tsm/models/TSM_kinetics_Flow_resnet50_shift8_blockres_avg_segment8_e50.pth. It should be OK for fine-tuning, but not for evaluation on Kinetics. I will try to provide a formal one in the future.

**Comment by jianghaojun** [comment]
Hi Dr Lin, how did you train the model using flow as the input modality？Is there any off-the-shelf codebase？
