### ISSUE TITLE
A question about optimizer policy

### ISSUE THREAD

**Issue by ZJUwangdaiyin** [mit-han-lab/temporal-shift-module#52]
Appreciated for your great work and kind code sharing!
I notice that there is a complex optimizer policy in the TSN model. A part of that is like: 
{'params': first_conv_weight, 'lr_mult': 5 if self.modality == 'Flow' else 1, 'decay_mult': 1,
             'name': "first_conv_weight"},
However, I suppose that the embedded pytorch SGD optimizer cannot identify the parameters like 'lr_mult' and 'decay_mult', which are from Caffe framework. Considering there is no specific function to override the 'step' func in the original SGD class, I deem that those complex optimizer policy is indeed without efficiency.
Please disabuse me if I misunderstand this part.

**Comment by tonylins** [comment]
Hi, firstly, these part of the code is directly taken from TSN codebase. In fact, I find that the optimizer policy does not make much difference.

Secondly, PyTorch SGD cannot identify these args. Therefore, we manually write the policy update in adjust_learning_rate.

Feel free to reopen if you have other questions.
