### ISSUE TITLE
Error when running online demo main.py

### ISSUE THREAD

**Issue by WSPluta** [mit-han-lab/temporal-shift-module#63]
I'm getting this error when I try to execute python3 main.py within `~/temporal-shift-module/online_demo` folder..

```
Open camera...
<VideoCapture 0x7f2f0b2370>
Build transformer...
/usr/local/lib/python3.6/dist-packages/torchvision-0.5.0a0+85b8fbf-py3.6-linux-aarch64.egg/torchvision/transforms/transforms.py:220: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
Build Executor...
/home/bm/temporal-shift-module/online_demo/mobilenet_v2_tsm.py:95: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  x1, x2 = x[:, : c // 8], x[:, c // 8:]
Traceback (most recent call last):

  File "main.py", line 386, in <module>
    main()

  File "main.py", line 282, in main
    executor, ctx = get_executor()

  File "main.py", line 96, in get_executor
    return torch2executor(torch_module, torch_inputs, target)

  File "main.py", line 52, in torch2executor
    graph, tvm_module, params = torch2tvm_module(torch_module, torch_inputs, target)

  File "main.py", line 31, in torch2tvm_module
    torch.onnx.export(torch_module, torch_inputs, buffer, input_names=input_names, output_names=["o" + str(i) for i in range(len(torch_inputs))])

  File "/home/bm/.local/lib/python3.6/site-packages/torch/onnx/__init__.py", line 148, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)

  File "/home/bm/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)

  File "/home/bm/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 416, in _export
    fixed_batch_size=fixed_batch_size)

  File "/home/bm/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 296, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)

  File "/home/bm/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 135, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)

  File "/home/bm/.local/lib/python3.6/site-packages/torch/onnx/__init__.py", line 179, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)

  File "/home/bm/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 657, in _run_symbolic_function
    return op_fn(g, *inputs, **attrs)

  File "/home/bm/.local/lib/python3.6/site-packages/torch/onnx/symbolic_helper.py", line 129, in wrapper
    return fn(g, *args)

  File "/home/bm/.local/lib/python3.6/site-packages/torch/onnx/symbolic_opset9.py", line 1311, in slice
    raise RuntimeError('Unsupported: ONNX export of Slice with dynamic inputs. DynamicSlice '

RuntimeError: Unsupported: ONNX export of Slice with dynamic inputs. DynamicSlice is a deprecated experimental op. Please use statically allocated variables or export to a higher opset version.
```

**Comment by Ragavendrams** [comment]
I get the same issue too when running the online demo on the Jetson TX2.

**Comment by dionsaputra** [comment]
Hi @WSPluta, Have you get the solution of this problem?

**Comment by henry-y-c** [comment]
Have same issue. Rolling back torch==1.2.0 and torchvision==0.4.0 works for me.

**Comment by highvight** [comment]
Don't know if this helps, but the onnx exporter takes an opset argument. Perhaps try:

` torch.onnx.export(torch_module, torch_inputs, buffer, input_names=input_names, output_names=["o" + str(i) for i in range(len(torch_inputs))], opset_version=11)`

**Comment by poincarelee** [comment]
@WSPluta, @Ragavendrams @dionsaputra 
  hi, have you get solution of this problem? I got the same issue.

**Comment by dionsaputra** [comment]
I run online demo without using onnx

**Comment by poincarelee** [comment]
@dionsaputra Thanks for your reply. Could you tell me how you make it  or could you kindly give me any instruction or tips on running without onnx?  Should I delete code related to onnx in main.py ? I am not familiar with onnx.

**Comment by dionsaputra** [comment]
@poincarelee Yes, you can remove anything related with onnx and load the model using normal pytorch library

**Comment by poincarelee** [comment]
Thanks a lot. Your advice is a great idea, I will have a try on it.

**Comment by poincarelee** [comment]
I  have solved this problem. The solution is to export torch model with opset 10 instead of default opset 9, TVM does not really support some operators in opset 9. Additionally,  using a tool "onnx-simplifier" would be great help.

**Comment by ihshin227** [comment]
@poincarelee Could you tell me how you use "onnx-simplifier"?

**Comment by poincarelee** [comment]
you can search for it in github and then refer to the last part of  readme such as "pip install onnx-simplifier" and thus import it in your script, it's simple to use this tool.

**Comment by ihshin227** [comment]
thank you!

I try to use onnx-simplifier like below

```
from onnxsim import simplify
```

In torch2tvm_module, I add onnx-simplifier after the onnx.load_model
```
onnx_model = onnx.load_model(buffer)
onnx_model, _ = simplify(onnx_model)
```

However, in simplify function, I have met new error.
```
onnx.onnx_cpp2py_export.checker.ValidationError: Graph must be in single static assignment (SSA) form, however ‘698’ has been used as output names multiple times.
```

Did you have seen this error?

**Comment by poincarelee** [comment]
I havn't met with this error. Maybe you need to check that the torch model be exported to opeset 10?
Add "opset 10" to the onnx export function and try again.

**Comment by ihshin227** [comment]
I already try "opset 10".

I think that the version of packages may arise this error.

My environment as follows:
pytorch: 1.5.0
torchvision: 1.7.0
onnx: 1.7.0
tvm: 0.6.0
CUDA: 10.2
cuDNN: 8.0.0
OpenCV: 4.1.1

Are these quite different from yours?

**Comment by poincarelee** [comment]
My environment:
Pytorch=1.4.0
Torchvision=0.5.0
Onnx=1.7.0
Onnx-simplifier=0.2.9
Opencv=4.2.0.34
Incubator-tvm=0.6
cuda=10.1
cudnn=7.6
the version of pytorch, torchvision,onnx, tvm may matters.

**Comment by ihshin227** [comment]
Thanks a lot.
I change my Pytorch to 1.4.0, but still have a problem.

```
Open camera...
[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (933) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
<VideoCapture 0x7f456ba3b0>
Build transformer...
/usr/local/lib/python3.6/dist-packages/torchvision-0.6.0a0+b68adcf-py3.6-linux-aarch64.egg/torchvision/transforms/transforms.py:211: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
Build Executor...
/home/nvidia/temporal-shift-module/online_demo/mobilenet_v2_tsm.py:95: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  x1, x2 = x[:, : c // 8], x[:, c // 8:]
WARNING:root:Attribute momentum is ignored in relay.sym.batch_norm
WARNING:root:Attribute momentum is ignored in relay.sym.batch_norm
WARNING:root:Attribute momentum is ignored in relay.sym.batch_norm
WARNING:root:Attribute momentum is ignored in relay.sym.batch_norm
WARNING:root:Attribute momentum is ignored in relay.sym.batch_norm
WARNING:root:Attribute momentum is ignored in relay.sym.batch_norm
Traceback (most recent call last):

  File "main.py", line 393, in <module>
    main()

  File "main.py", line 289, in main
    executor, ctx = get_executor()

  File "main.py", line 103, in get_executor
    return torch2executor(torch_module, torch_inputs, target)

  File "main.py", line 59, in torch2executor
    graph, tvm_module, params = torch2tvm_module(torch_module, torch_inputs, target)

  File "main.py", line 40, in torch2tvm_module
    relay_module, params = tvm.relay.frontend.from_onnx(onnx_model, shape=input_shapes)

  File "/usr/local/lib/python3.6/dist-packages/tvm-0.6.0-py3.6-linux-aarch64.egg/tvm/relay/frontend/onnx.py", line 1497, in from_onnx
    mod, params = g.from_onnx(graph, opset)

  File "/usr/local/lib/python3.6/dist-packages/tvm-0.6.0-py3.6-linux-aarch64.egg/tvm/relay/frontend/onnx.py", line 1325, in from_onnx
    op = self._convert_operator(op_name, inputs, attr, opset)

  File "/usr/local/lib/python3.6/dist-packages/tvm-0.6.0-py3.6-linux-aarch64.egg/tvm/relay/frontend/onnx.py", line 1425, in _convert_operator
    sym = convert_map[op_name](inputs, attrs, self._params)

  File "/usr/local/lib/python3.6/dist-packages/tvm-0.6.0-py3.6-linux-aarch64.egg/tvm/relay/frontend/onnx.py", line 793, in _impl_v10
    ends = params[get_name(inputs[2])].asnumpy()

KeyError: ''
```

**Comment by poincarelee** [comment]
emm, put ''import onnx" before "import torch" and try again, if not work, reinstall tvm  using "git clone -b 0.6 " command in the readme. You'd better post the code how you use onnx-simplifier, seems still op problems.

**Comment by ihshin227** [comment]
Thank you for your help! You are my hero!
When I import onnx before import torch, online demo is working.

here is my code
```
import numpy as np
import os
from typing import Tuple
import io
import tvm
import tvm.relay
import time
import cv2
import onnx
import torch
import torchvision
import torch.onnx
from PIL import Image, ImageOps
import tvm.contrib.graph_runtime as graph_runtime
from mobilenet_v2_tsm import MobileNetV2
from onnxsim import simplify

SOFTMAX_THRES = 0
HISTORY_LOGIT = True
REFINE_OUTPUT = True

def torch2tvm_module(torch_module: torch.nn.Module, torch_inputs: Tuple[torch.Tensor, ...], target):
    torch_module.eval()
    input_names = []
    input_shapes = {}
    with torch.no_grad():
        for index, torch_input in enumerate(torch_inputs):
            name = "i" + str(index)
            input_names.append(name)
            input_shapes[name] = torch_input.shape
        buffer = io.BytesIO()
        torch.onnx.export(torch_module, torch_inputs, buffer, input_names=input_names, output_names=["o" + str(i) for i in range(len(torch_inputs))], opset_version=10)
        outs = torch_module(*torch_inputs)
        buffer.seek(0, 0)
        onnx_model = onnx.load_model(buffer)
        onnx_model, _ = simplify(onnx_model)
        relay_module, params = tvm.relay.frontend.from_onnx(onnx_model, shape=input_shapes)
    with tvm.relay.build_config(opt_level=3):
        graph, tvm_module, params = tvm.relay.build(relay_module, target, params=params)
    return graph, tvm_module, params
```

**Comment by tonylins** [comment]
Hi guys, sorry for the painful experience when working on the online demo. I believe the version mismatch could be the problem here.

Is there anyone interested in sending a pull request to help the others set up the environment later, according to the solution above? Thanks!

**Comment by poincarelee** [comment]
@tonylins Hi, I have written a file in my repository forked from yours, but I don't know how to pull request.

**Comment by poincarelee** [comment]
https://github.com/poincarelee/temporal-shift-module/tree/poincarelee-running-online-demo

**Comment by Nauman007** [comment]
hello!
can i run this demo on my personal-pc? without jetson nano ?
if yes then how ?
I  am facing he following error... i have done the above solutions..

![Screenshot from 2020-07-03 19-14-09](https://user-images.githubusercontent.com/32773342/86477234-70ca3980-bd61-11ea-98a4-0d928a8f3eb7.png)

**Comment by Nauman007** [comment]
people who are trying to run it on personal PC's(on cpu) can email at : iemnauman.akram@gmail.com
I will soon make a file and share here the complete process.

The above comments helped me a lot in resolving issues.

Regards.

**Comment by txf-** [comment]
Hi @poincarelee, how did you install onnx-simplify? I get an error with the onnxruntime dependency:

```
pip3 install 'onnx-simplifier==0.2.9'

Collecting onnx-simplifier==0.2.9
  Using cached https://files.pythonhosted.org/packages/19/f1/4b188f4dacc45b69e48605f5232a9f22616656fd189dcc04369b516d818b/onnx-simplifier-0.2.9.tar.gz
Collecting onnx (from onnx-simplifier==0.2.9)
Collecting onnxruntime>=1.2.0 (from onnx-simplifier==0.2.9)
  Could not find a version that satisfies the requirement onnxruntime>=1.2.0 (from onnx-simplifier==0.2.9) (from versions: )
No matching distribution found for onnxruntime>=1.2.0 (from onnx-simplifier==0.2.9)
```

did you compile onnxruntime from source?

**Comment by tonylins** [comment]
Hi, I have updated the repo to use `onnx-simplifier` and some other minor changes. It should now eliminate the error. Feel free to reopen if the error persists. Thanks!

**Comment by czqInNanjing** [comment]
Hi, when I am install onnxsimplifier, I remove requirement 'onnxruntime >= 1.2.0' in setup.py as the readme shown. 
But I fail to run the demo and it shows the error like it:

**Comment by dandingol03** [comment]
> people who are trying to run it on personal PC's(on cpu) can email at : [iemnauman.akram@gmail.com](mailto:iemnauman.akram@gmail.com)
> I will soon make a file and share here the complete process.
> 
> The above comments helped me a lot in resolving issues.
> 
> Regards.

hi, @Nauman007, can you share the file with me? i was trying to run it on pc(on cpu)

**Comment by jack-jun** [comment]
> @tonylins I am using Jetson tx2 Hi, when I am install onnxsimplifier, I remove requirement 'onnxruntime >= 1.2.0' in setup.py as the readme shown. But I fail to run the demo and it shows the error like it:
> 
> ```
> Open camera...
> <VideoCapture 0x7f05923cf0>
> Build transformer...
> /usr/local/lib/python3.6/dist-packages/torchvision-0.3.0-py3.6-linux-aarch64.egg/torchvision/transforms/transforms.py:209: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
> Build Executor...
> /home/nvidia/Downloads/temporal-shift-module-master/online_demo/mobilenet_v2_tsm.py:95: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   x1, x2 = x[:, : c // 8], x[:, c // 8:]
> Traceback (most recent call last):
> 
>   File "main.py", line 389, in <module>
>     main()
> 
>   File "main.py", line 285, in main
>     executor, ctx = get_executor()
> 
>   File "main.py", line 99, in get_executor
>     return torch2executor(torch_module, torch_inputs, target)
> 
>   File "main.py", line 55, in torch2executor
>     graph, tvm_module, params = torch2tvm_module(torch_module, torch_inputs, target)
> 
>   File "main.py", line 35, in torch2tvm_module
>     from onnxsim import simplify
> 
>   File "/home/nvidia/.local/lib/python3.6/site-packages/onnxsim/__init__.py", line 1, in <module>
>     from onnxsim.onnx_simplifier import simplify
> 
>   File "/home/nvidia/.local/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 11, in <module>
>     import onnxruntime as rt  # type: ignore
> 
> ModuleNotFoundError: No module named 'onnxruntime'
> ```

Did you find a solution?
Thanks

**Comment by jack-jun** [comment]
> @tonylins I am using Jetson tx2 Hi, when I am install onnxsimplifier, I remove requirement 'onnxruntime >= 1.2.0' in setup.py as the readme shown. But I fail to run the demo and it shows the error like it:
> 
> ```
> Open camera...
> <VideoCapture 0x7f05923cf0>
> Build transformer...
> /usr/local/lib/python3.6/dist-packages/torchvision-0.3.0-py3.6-linux-aarch64.egg/torchvision/transforms/transforms.py:209: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
> Build Executor...
> /home/nvidia/Downloads/temporal-shift-module-master/online_demo/mobilenet_v2_tsm.py:95: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
>   x1, x2 = x[:, : c // 8], x[:, c // 8:]
> Traceback (most recent call last):
> 
>   File "main.py", line 389, in <module>
>     main()
> 
>   File "main.py", line 285, in main
>     executor, ctx = get_executor()
> 
>   File "main.py", line 99, in get_executor
>     return torch2executor(torch_module, torch_inputs, target)
> 
>   File "main.py", line 55, in torch2executor
>     graph, tvm_module, params = torch2tvm_module(torch_module, torch_inputs, target)
> 
>   File "main.py", line 35, in torch2tvm_module
>     from onnxsim import simplify
> 
>   File "/home/nvidia/.local/lib/python3.6/site-packages/onnxsim/__init__.py", line 1, in <module>
>     from onnxsim.onnx_simplifier import simplify
> 
>   File "/home/nvidia/.local/lib/python3.6/site-packages/onnxsim/onnx_simplifier.py", line 11, in <module>
>     import onnxruntime as rt  # type: ignore
> 
> ModuleNotFoundError: No module named 'onnxruntime'
> ```

Did you find a solution?
Thanks
