### ISSUE TITLE
Have you ever tried to pretrain TSM-Bniception on Kinetics.

### ISSUE THREAD

**Issue by White1973** [mit-han-lab/temporal-shift-module#73]
If you have done it, when will the parameters of TSM-Bniception pretrained on Kinetics be released?

**Comment by tonylins** [comment]
Hi, we did not use BN-Inception, since it is a relatively old model. But we do have a converted model, which you can find here:   https://github.com/mit-han-lab/temporal-shift-module/blob/832a758f0c1e4a835cb0a47d957eff776d35dd91/archs/bn_inception.py#L10
