### ISSUE TITLE
Error in online_demo (nvcc missing)

### ISSUE THREAD

**Issue by Gelb153** [mit-han-lab/temporal-shift-module#75]
Hello, 

I have installed all the software as described in the instraction on a Jetson Nano. But when I run the main.py in online_demo (pyhton3 main.py) I get a very long error message. (see below). 

The file "nvcc" seems to be missing. Does anyone know how I can correct the error  

File "main.py", line 395, in <module>
    main()

  File "main.py", line 287, in main
    executor, ctx = get_executor()

  File "main.py", line 96, in get_executor
    return torch2executor(torch_module, torch_inputs, target)

  File "main.py", line 52, in torch2executor
    graph, tvm_module, params = torch2tvm_module(torch_module, torch_inputs, target)

  File "main.py", line 37, in torch2tvm_module
    graph, tvm_module, params = tvm.relay.build(relay_module, target, params=params)

  File "/usr/local/lib/python3.6/dist-packages/tvm-0.7.dev1-py3.6-linux-aarch64.egg/tvm/relay/build_module.py", line 251, in build
    graph_json, mod, params = bld_mod.build(mod, target, target_host, params)

  File "/usr/local/lib/python3.6/dist-packages/tvm-0.7.dev1-py3.6-linux-aarch64.egg/tvm/relay/build_module.py", line 120, in build
    self._build(mod, target, target_host)

  File "tvm/_ffi/_cython/./packed_func.pxi", line 312, in tvm._ffi._cy3.core.PackedFuncBase.__call__

  File "tvm/_ffi/_cython/./packed_func.pxi", line 247, in tvm._ffi._cy3.core.FuncCall

  File "tvm/_ffi/_cython/./packed_func.pxi", line 236, in tvm._ffi._cy3.core.FuncCall3

  File "tvm/_ffi/_cython/./base.pxi", line 160, in tvm._ffi._cy3.core.CALL

tvm._ffi.base.TVMError: Traceback (most recent call last):
  [bt] (8) /usr/local/lib/python3.6/dist-packages/tvm-0.7.dev1-py3.6-linux-aarch64.egg/tvm/libtvm.so(std::_Function_handler<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*), tvm::relay::backend::RelayBuildModule::GetFunction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#3}>::_M_invoke(std::_Any_data const&, tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&)+0x2c) [0x7f99ed9bcc]
  [bt] (7) /usr/local/lib/python3.6/dist-packages/tvm-0.7.dev1-py3.6-linux-aarch64.egg/tvm/libtvm.so(tvm::relay::backend::RelayBuildModule::GetFunction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tvm::runtime::ObjectPtr<tvm::runtime::Object> const&)::{lambda(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*)#3}::operator()(tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*) const+0x1ac) [0x7f99ed9ac4]
  [bt] (6) /usr/local/lib/python3.6/dist-packages/tvm-0.7.dev1-py3.6-linux-aarch64.egg/tvm/libtvm.so(tvm::relay::backend::RelayBuildModule::BuildRelay(tvm::IRModule, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::runtime::NDArray, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, tvm::runtime::NDArray> > > const&)+0xb6c) [0x7f99ed93dc]
  [bt] (5) /usr/local/lib/python3.6/dist-packages/tvm-0.7.dev1-py3.6-linux-aarch64.egg/tvm/libtvm.so(tvm::build(tvm::Map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, tvm::IRModule, void, void> const&, tvm::Target const&, tvm::BuildConfig const&)+0x388) [0x7f99b18978]
  [bt] (4) /usr/local/lib/python3.6/dist-packages/tvm-0.7.dev1-py3.6-linux-aarch64.egg/tvm/libtvm.so(tvm::build(tvm::Map<tvm::Target, tvm::IRModule, void, void> const&, tvm::Target const&, tvm::BuildConfig const&)+0x448) [0x7f99b18120]
  [bt] (3) /usr/local/lib/python3.6/dist-packages/tvm-0.7.dev1-py3.6-linux-aarch64.egg/tvm/libtvm.so(tvm::codegen::Build(tvm::IRModule, tvm::Target const&)+0x26c) [0x7f99b46444]
  [bt] (2) /usr/local/lib/python3.6/dist-packages/tvm-0.7.dev1-py3.6-linux-aarch64.egg/tvm/libtvm.so(std::_Function_handler<void (tvm::runtime::TVMArgs, tvm::runtime::TVMRetValue*), tvm::runtime::TypedPackedFunc<tvm::runtime::Module (tvm::IRModule)>::AssignTypedLambda<tvm::runtime::Module (*)(tvm::IRModule)>(tvm::runtime::Module (*)(tvm::IRModule))::{lambda(tvm::runtime::TVMArgs const&, tvm::runtime::TVMRetValue*)#1}>::_M_invoke(std::_Any_data const&, tvm::runtime::TVMArgs&&, tvm::runtime::TVMRetValue*&&)+0xfc) [0x7f99b90744]
  [bt] (1) /usr/local/lib/python3.6/dist-packages/tvm-0.7.dev1-py3.6-linux-aarch64.egg/tvm/libtvm.so(tvm::codegen::BuildCUDA(tvm::IRModule)+0x760) [0x7f99fc09f8]
  [bt] (0) /usr/local/lib/python3.6/dist-packages/tvm-0.7.dev1-py3.6-linux-aarch64.egg/tvm/libtvm.so(+0xc60d28) [0x7f9a022d28]
  File "tvm/_ffi/_cython/./packed_func.pxi", line 55, in tvm._ffi._cy3.core.tvm_callback
  File "/usr/local/lib/python3.6/dist-packages/tvm-0.7.dev1-py3.6-linux-aarch64.egg/tvm/autotvm/measure/measure_methods.py", line 597, in tvm_callback_cuda_compile
    ptx = nvcc.compile_cuda(code, target=target, arch=AutotvmGlobalScope.current.cuda_target_arch)
  File "/usr/local/lib/python3.6/dist-packages/tvm-0.7.dev1-py3.6-linux-aarch64.egg/tvm/contrib/nvcc.py", line 96, in compile_cuda
    cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nvcc': 'nvcc'

**Comment by jianghancheng** [comment]
@Gelb153 Do you solve the problem? How to do it?

**Comment by Gelb153** [comment]
Unfortunately I have not solved the problem. All tries have not been successful so far

**Comment by Summit9** [comment]
I had the same issue that I fixed with the following steps:

> sudo vim ~/.bashrc
> export PATH=/usr/local/cuda/bin:$PATH export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
> source ~/.bashrc

Hope this helps!

**Comment by Gelb153** [comment]
Greate, Summit9 !!! Your solution works, after a restart of the jetson. Thanky you very much.
