### ISSUE TITLE
Error during downloading pre-trained models

### ISSUE THREAD

**Issue by KimManjin** [mit-han-lab/temporal-shift-module#78]
I've trying to download pre-trained models.
However, all link seem to be blocked.
Please check that if links are available properly.

Thanks.

**Comment by qlz58793** [comment]
I've met this problem, too. :(

**Comment by tonylins** [comment]
Hi, the file server that hosts the pre-trained weights are down. We are working on the fix. Sorry for the waiting.

**Comment by tonylins** [comment]
The links are fixed now. Let me know if there is any problem. Thanks!
