### ISSUE TITLE
How to train a RGB + Flow model?

### ISSUE THREAD

**Issue by sunnymoon155** [mit-han-lab/temporal-shift-module#8]
Thanks for the repo! I'm wondering is there a command to train a RGB + Flow model on a pretrained model?

**Comment by tonylins** [comment]
Hi, following the common protocol, you need to train the RGB and Flow model separately and ensemble the outputs from the two models.

**Comment by sunnymoon155** [comment]
@tonylins you mean use two models to do test, and fuse two outputs to get the final result? Or, fuse the output in training state?

**Comment by tonylins** [comment]
Yes, we just directly average the outputs of the two models during testing. It could possibly achieve  a better result if we consider the two-stream fusion during training, but that is beyond the scope of our paper.
