### ISSUE TITLE
Pretrained models are not accessible

### ISSUE THREAD

**Issue by nerdysandy17** [mit-han-lab/temporal-shift-module#80]
Hello, unfortunately all the links for the pretrained models are not accessible. Could you please fix this issue or provide an alternative way to download the checkpoints?

**Comment by tonylins** [comment]
Hi, the file server that hosts the pre-trained weights is down. We are working on the fix. Sorry for the waiting.

**Comment by juanmanpr** [comment]
Hi @tonylins, thanks for your efforts. Is it possible you provide an alternative way to download the checkpoints? I am looking at the TSM kinetics pretrained weights and do not seem to be available.
Really appreciate it.

**Comment by Fritskee** [comment]
@tonylins Would it be possible to share the models through a different link? (some common repository where we can download the models)

**Comment by tonylins** [comment]
Definitely, I will work on it now. I should be able to restore most of it.

**Comment by tonylins** [comment]
The links are fixed now. Let me know if there is any problem. Thanks!

**Comment by Fritskee** [comment]
I was able to download them! Thanks for reacting and solving the issue so fast!
