### ISSUE TITLE
training with and without TSM correctly

### ISSUE THREAD

**Issue by yuvals1** [mit-han-lab/temporal-shift-module#82]
Hi, 
this is how you train with TSM:
python main.py ucf101 RGB \
     --arch resnet50 --num_segments 8 \
     --gd 20 --lr 0.001 --lr_steps 10 20 --epochs 25 \
     --batch-size 64 -j 16 --dropout 0.8 --consensus_type=avg --eval-freq=1 \
     --shift --shift_div=8 --shift_place=blockres \

is the right way to train without TSM is to remove this line: 
-shift --shift_div=8 --shift_place=blockres \
?

**Comment by tonylins** [comment]
Yes.
