### ISSUE TITLE
different num segments in TSM and TSN comparison

### ISSUE THREAD

**Issue by yuvals1** [mit-han-lab/temporal-shift-module#84]
hi, is there a reason why the number of segments used in creating the pretrained architectures in the example of tasing TSN vs TSM  is different (8 vs 5)? shouldn't they be the same?
# test TSN
python test_models.py kinetics \
    --weights=pretrained/TSM_kinetics_RGB_resnet50_avg_segment5_e50.pth \
    --test_segments=8 --test_crops=1 \
    --batch_size=64

# test TSM
python test_models.py kinetics \
    --weights=pretrained/TSM_kinetics_RGB_resnet50_shift8_blockres_avg_segment8_e50.pth \
    --test_segments=8 --test_crops=1 \
    --batch_size=64

**Comment by tonylins** [comment]
We actually tried using both 5 & 8 for TSN, and the results are the similar. As suggested by the TSN authors, using fewer frames for training could possibly reduce overfitting.
