### ISSUE TITLE
How to create optical flow data for training?

### ISSUE THREAD

**Issue by qlz58793** [mit-han-lab/temporal-shift-module#85]
before this, I have changed the code in vid2img_kinetics.py to create dataset of frame format to train TSM and get accuracy of 94.528. 
Now I want to train TSM on UCF101 based on optical flow. 
In data_config I found img_{:05d}.jpg, flow_{}_{:05d}.jpg:

    filename_categories = 'UCF101/labels/classInd.txt'
    if modality == 'RGB':
        root_data = ROOT_DATASET + 'UCF101/jpg'
        filename_imglist_train = 'UCF101/file_list/ucf101_rgb_train_split_1.txt'
        filename_imglist_val = 'UCF101/file_list/ucf101_rgb_val_split_1.txt'
        prefix = 'img_{:05d}.jpg'
    elif modality == 'Flow':
        root_data = ROOT_DATASET + 'UCF101/jpg'
        filename_imglist_train = 'UCF101/file_list/ucf101_flow_train_split_1.txt'
        filename_imglist_val = 'UCF101/file_list/ucf101_flow_val_split_1.txt'
        prefix = 'flow_{}_{:05d}.jpg'
    else:
        raise NotImplementedError('no such modality:' + modality)
    return filename_categories, filename_imglist_train, filename_imglist_val, root_data, prefix

However, I haven't found the script to create optical flow dataset. 
How can I do this, to create the right optical-flow dataset of ucf101? 
Thanks a lot!

**Comment by Andy1621** [comment]
Although I never try to extract optical flow, I think you can refer to mmaction. https://github.com/open-mmlab/mmaction/blob/master/data_tools/ucf101/PREPARING_UCF101.md

**Comment by qlz58793** [comment]
> Although I never try to extract optical flow, I think you can refer to mmaction. https://github.com/open-mmlab/mmaction/blob/master/data_tools/ucf101/PREPARING_UCF101.md

thanks！

**Comment by Fritskee** [comment]
@qlz58793 Did the method provided by @Andy1621 work correctly for you in the end? I'm also trying to get optical flow working (on a different dataset).
