### ISSUE TITLE
Pretrained imagenet model is unavailable,

### ISSUE THREAD

**Issue by z13974509906** [mit-han-lab/temporal-shift-module#86]
https://github.com/mit-han-lab/temporal-shift-module/blob/d6da93d7a1dbff5a0dc54da8b1ae9dae28127329/archs/mobilenet_v2.py#L141

the model is unavailabel, could you check it?

**Comment by tonylins** [comment]
Hi, from my side it is still available. Please check downloading from a web browser, and make sure your Internet connection is not blocked.
