### ISSUE TITLE
on-line demo problem: "bilinear_sample_nchw" could not import

### ISSUE THREAD

**Issue by poincarelee** [mit-han-lab/temporal-shift-module#89]
I build TVM and other files according to on-line-demo readme, however ,when I run the main.py, an error always occurs: bilinear_sample_nchw could not be imported from ..cpp.util.  I found several ways through Internet, many methods mentioned did not work for me. 
Could you tell me how to solve it ? I think this is a basic problem and the temporal-shift-module building should not be so complicated.

**Comment by z14git** [comment]
try to run this command fisrt

`export LD_LIBRARY_PATH=<your_python_packages_install_path>/topi-0.6.dev0-py3.6.egg/topi`

 before you run the python script

**Comment by poincarelee** [comment]
yes，I have solved this problem by coping libtvm_topi.so to the directory python virtual environment.  Seems the  readme.md  has updated this issue.  I will close this issue.
