### ISSUE TITLE
fine-tune on hmdb

### ISSUE THREAD

**Issue by zhengshou** [mit-han-lab/temporal-shift-module#91]
Neat work!

There is sample command for finetuning on UCF. Would you also share the command or training hyper-parameters for finetuning on HMDB?

Thanks a lot!

**Comment by Andy1621** [comment]
I think you can just use the same codes.

**Comment by tonylins** [comment]
Hi, you can try using the same hyper-parameters as UCF. That results should be close.

**Comment by zhengshou** [comment]
Thanks!

How about the Flow modality? Can I use the same hyper-parameters as well?

**Comment by tonylins** [comment]
Hi, sorry for the late reply. If you are fine-tuning from a pretrained Kinetics Flow model, you should be able to use the same hyper-parameter. But personally I did not actually run that.

**Comment by tonylins** [comment]
Close due to inactivity, feel free to reopen.
