### ISSUE TITLE
Dose UCF101  dataset need to extract frames when I train the  network on it ?

### ISSUE THREAD

**Issue by Snowballing** [mit-han-lab/temporal-shift-module#97]
Thanks for you to public your code ! If  the UCF101 dataset need to extract frames ,the "tools/vid2img_kinetics.py" didn't woark .It  just  build  a lot of empty  folders.  can you tell me the version of the  FFmpeg.  I think it the  the key  cuase.

**Comment by tonylins** [comment]
Hi, you can check the TSN repo (https://github.com/yjxiong/temporal-segment-networks). It contains detailed guide to process UCF data.

Meanwhile, you can also change the `vid2img_kinetics.py` code to extract frames on UCF. I tried different versions of FFmpeg, and they both work fine. What is the error message that you got?

**Comment by wzy1845** [comment]
@Snowballing Hi, I have the same issue. Have you solved it? Hope to get your reply.

**Comment by wzy1845** [comment]
> Hi, you can check the TSN repo (https://github.com/yjxiong/temporal-segment-networks). It contains detailed guide to process UCF data.
> 
> Meanwhile, you can also change the `vid2img_kinetics.py` code to extract frames on UCF. I tried different versions of FFmpeg, and they both work fine. What is the error message that you got?

Thanks for  your code and advice ! I tried the TSN repo（https://github.com/yjxiong/temporal-segment-networks#extract-frames-and-optical-flow-images）, but  just build a lot of empty folders.

**Comment by tonylins** [comment]
I will close the issue now due to inactivity. Feel free to reopen if the problem persists.

**Comment by Snowballing** [comment]
OK，thanks for your answer!

**Comment by Nauman007** [comment]
hi @Snowballing  did u find/write the code for UCF101 to extract frames and labels?

**Comment by Snowballing** [comment]
I used the author's code finally

**Comment by Nauman007** [comment]
can u please guide me about the input parameters of this model? and some guides on how can i train this model on custom dataset. any help would be appreciated.

Actually i am new deep learning models and pytorch.
I am aiming to use this model in my capstone project.

**Comment by Nauman007** [comment]
@tonylins please give some guidance in training a custom dataset.. and about the input paramters of TSM.

**Comment by tonylins** [comment]
Hi @Nauman007 , training on a new dataset is kind of straightforward. You need to first prepare the dataset following the guide and then perform training. What is the difficulty you encountered?

**Comment by Nauman007** [comment]
@tonylins  thanks for your reply..
I am having difficulty in preparing the dataset (UCF101)   
when i try to extract the frames i get a bunch of empty directories. Frames donot get extracted.

Can u (if possible) guide me in a way seeing me as a beginner.

**Comment by Nauman007** [comment]
how do i prepare my dataset for TSM ?
and if i want to use your module on UCF-crime dataset would that be a good choice ? what are your suggestions?
