### ISSUE TITLE
online demo error  with  onnx opset

### ISSUE THREAD

**Issue by poincarelee** [mit-han-lab/temporal-shift-module#98]
I was running online demo after build TSM according to readme.md, when I run "python main.py", 
an error occurs:" unsupported export of dynamic inputs. The dynamic slice is deprecated experimental op  ,pls change to higher op version" ,   So I change the default opset version to 10/11/12, however , it says " keyerror: ' ' ",  it seems there is confliction somewhere between the online demo and onnx, but I could not locate it. Could you tell me how to solve it? Thanks.
My environment is as follows:
pytorch=1.4.0 torchvision=0.5.0 onnx=1.5.0 and I also tried different versions for pytorch and onnx such as pytorch=1.5.0,onnx=1.7.0/1.6.0.

**Comment by tonylins** [comment]
Hi, could you check the link to see if the error persists? There might be some version mismatch.

https://github.com/jaqif/temporal-shift-module/commit/c7679dcf363c041fb45614c44b617a70f58ffebe.

**Comment by poincarelee** [comment]
Thanks for your reply,  I follow the instruction in the link, however, the same error persists.

**Comment by poincarelee** [comment]
hi, @tonylins , could you kindly refer to #63?  Seems this problem has not been solved. Actually, my problem is the same as #63. I think it may be a common problem. Thanks a lot.

**Comment by poincarelee** [comment]
I have solved this problem. And thus I will close it.

**Comment by acabadw22** [comment]
@poincarelee  did you solve it?

**Comment by poincarelee** [comment]
Yes, I have solved the problem. I think maybe you can try to debug the parameter"ends" and see if there's anything unexpected.  Most of my problems are about package version. As your problem is about onnx,  you can try to use a tool"onnx-simplifier", which will solve a lot of  problems on onnx operators, and then try different opset versions.  Maybe you can refer to #63 .
